import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const elmsSans = localFont({
  src: [
    {
      path: "./fonts/ElmsSans-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/ElmsSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ElmsSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ElmsSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-elms-sans",
});

const jetbrainsMono = localFont({
  src: [
    {
      path: "./fonts/JetBrainsMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/JetBrainsMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-jetbrains-mono",
});

const geist = localFont({
  src: [
    {
      path: "./fonts/Geist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Geist-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Geist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${elmsSans.variable} ${jetbrainsMono.variable} ${geist.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}

