import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs/promises';
import * as path from 'path';
import 'dotenv/config';

// explicit process fallback for common lint issues in dev containers
const env = typeof process !== 'undefined' ? process.env : ({} as any);

const NEW_URL = env.SUPABASE_URL;
const NEW_KEY = env.SUPABASE_KEY;

const supabase = createClient(NEW_URL, NEW_KEY, {
  auth: { persistSession: false }
});

const REPAIR_FILE = path.join(typeof process !== 'undefined' ? process.cwd() : '.', 'auto_repair_identities.sql');

async function scanForMissingIdentities() {
  console.log('🔍 Scanning New Database for missing Identities and Defaults...');

  // Since we don't have a raw SQL RPC, we will try to infer from common candidates 
  // and check the schema metadata via the PostgREST API if possible, 
  // or use the known table list from our migration files.

  const TABLE_LIST = [
    'user_profiles', 'user_state', 'telegram_accounts', 'telegram_codes', 
    'user_tokens', 'tasks', 'chats', 'chat_messages', 'suggestion_history', 
    'checkins', 'revenue_events', 'wallet_events', 'tracked_wallet_state', 
    'simulation_logs', 'indexer_state', 'prices', 'notification_delivery_log', 
    'points_history', 'chat_points', 'referrals', 'feedback', 'documents', 
    'events', 'events_log', 'monitored_wallets', 'productivity_stats', 
    'social_tasks', 'task_drafts', 'task_history', 'users_monitor', 'waitlist_emails'
  ];

  let repairSql = `-- 🤖 AUTO-GENERATED IDENTITY REPAIR SQL
-- Use this to ensure every table has an automatic ID generator.
-- Generated at: ${new Date().toISOString()}

`;

  console.log(`\n📋 Analyzing ${TABLE_LIST.length} tables...`);

  for (const table of TABLE_LIST) {
    try {
      // We try to "peek" at the columns naming and types
      // In a real PG environment we'd query information_schema.
      // Here we will generate a defensive script that adds the identity ONLY if missing.

      repairSql += `-- Processing ${table}...\n`;
      repairSql += `DO $$\nBEGIN\n`;
      
      // Determine if it uses ID (Numeric) or Chat_ID/ID (UUID)
      // We'll apply both logic paths defensively
      
      repairSql += `  -- Fix Numeric ID if it is a BIGINT/INT and has no sequence\n`;
      repairSql += `  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = '${table}' AND column_name = 'id' AND (data_type = 'bigint' OR data_type = 'integer') AND is_identity = 'NO' AND column_default IS NULL) THEN\n`;
      repairSql += `    ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;\n`;
      repairSql += `    PERFORM setval(pg_get_serial_sequence('${table}', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM ${table};\n`;
      repairSql += `  END IF;\n\n`;

      repairSql += `  -- Fix UUID ID if it lacks a default\n`;
      repairSql += `  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = '${table}' AND column_name = 'id' AND data_type = 'uuid' AND column_default IS NULL) THEN\n`;
      repairSql += `    ALTER TABLE ${table} ALTER COLUMN id SET DEFAULT gen_random_uuid();\n`;
      repairSql += `  END IF;\n\n`;

      repairSql += `  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = '${table}' AND column_name = 'chat_id' AND data_type = 'uuid' AND column_default IS NULL) THEN\n`;
      repairSql += `    ALTER TABLE ${table} ALTER COLUMN chat_id SET DEFAULT gen_random_uuid();\n`;
      repairSql += `  END IF;\n`;

      repairSql += `END $$;\n\n`;

    } catch (e) {}
  }

  await fs.writeFile(REPAIR_FILE, repairSql);
  console.log(`\n✨ Identity Repair SQL generated: ${REPAIR_FILE}`);
  console.log('\n🚀 NEXT STEP:');
  console.log('   Run the contents of auto_repair_identities.sql in your Supabase Dashboard.');
}

scanForMissingIdentities();
