import "dotenv/config";

const NEW_URL = process.env.SUPABASE_URL || process.env.NEW_SUPABASE_URL!;
const PAT = process.env.SUPABASE_PAT || "sbp_3eebf6fb2f93b0795a099f9b7bbf5f153c0dbc15";

const newProjectRef = new URL(NEW_URL).hostname.split(".")[0];

async function runSQLOnNewProject(sql: string) {
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${newProjectRef}/database/query`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PAT}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: sql }),
    }
  );

  if (!res.ok) {
    const err = await res.text();
    console.error(`  ❌ Failed to execute SQL: ${err}`);
    return null;
  }
  return res.json();
}

async function run() {
  console.log("🚀 Applying specific Primary Keys to remainder tables...");

  const queries = [
    // 1. Existing column PKs
    `ALTER TABLE public.chats ADD PRIMARY KEY (chat_id);`,
    `ALTER TABLE public.user_profiles ADD PRIMARY KEY (wallet_address);`,
    `ALTER TABLE public.user_state ADD PRIMARY KEY (wallet_address);`,
    
    // 2. Add an ID column for log/monitor tables that lack a single unique identifier column
    `ALTER TABLE public.recent_activity ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;`,
    `ALTER TABLE public.users_monitor ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;`
  ];

  for (const sql of queries) {
    process.stdout.write(`Executing: ${sql.substring(0, 50)}... `);
    const res = await runSQLOnNewProject(sql);
    if (res) console.log("✅");
  }
  
  console.log("Done fixing the primary keys.");
}

run().catch(console.error);
