/**
 * seed_schema.ts
 *
 * Auto-discovers the schema from the OLD Supabase project via its OpenAPI spec,
 * then creates all tables in the NEW Supabase project using the Management API.
 *
 * Run AFTER setting NEW_SUPABASE_URL and NEW_SUPABASE_SERVICE_KEY in .env
 *
 * Usage:
 *   npx tsx scripts/seed_schema.ts
 */

import "dotenv/config";

// ─── Credentials ──────────────────────────────────────────────────────────────

const OLD_URL = process.env.SUPABASE_URL!;
const OLD_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.SUPABASE_SERVICE_KEY ||
  process.env.SUPABASE_KEY!;

const NEW_URL = process.env.NEW_SUPABASE_URL!;
const NEW_KEY = process.env.NEW_SUPABASE_SERVICE_KEY!;

// Your Supabase personal access token (from supabase.com/dashboard/account/tokens)
// Used to call the Management API to run raw SQL on the new project
const PAT = process.env.SUPABASE_PAT || "sbp_3eebf6fb2f93b0795a099f9b7bbf5f153c0dbc15";

if (!OLD_URL || !OLD_KEY || !NEW_URL || !NEW_KEY) {
  console.error("❌ Missing credentials in .env — need SUPABASE_URL, SUPABASE_KEY, NEW_SUPABASE_URL, NEW_SUPABASE_SERVICE_KEY");
  process.exit(1);
}

// Extract project ref from URL: https://<ref>.supabase.co
const newProjectRef = new URL(NEW_URL).hostname.split(".")[0];

// ─── OpenAPI type → PostgreSQL type mapping ───────────────────────────────────

function toPostgresType(prop: any): string {
  const { type, format } = prop;

  if (format === "uuid") return "uuid";
  if (format === "int8" || format === "bigint") return "bigint";
  if (format === "int4" || format === "integer") return "integer";
  if (format === "int2" || format === "smallint") return "smallint";
  if (format === "float4" || format === "real") return "real";
  if (format === "float8" || format === "double precision") return "double precision";
  if (format === "numeric") return "numeric";
  if (format === "bool" || type === "boolean") return "boolean";
  if (format === "timestamptz") return "timestamptz";
  if (format === "timestamp") return "timestamp";
  if (format === "date") return "date";
  if (format === "time") return "time";
  if (format === "json" || format === "jsonb" || type === "object") return "jsonb";
  if (format === "text" || type === "string") return "text";

  // arrays
  if (type === "array") return "jsonb";

  return "text";
}

// ─── Fetch OpenAPI spec from old project ─────────────────────────────────────

async function fetchOpenAPISpec(): Promise<any> {
  const res = await fetch(`${OLD_URL}/rest/v1/`, {
    headers: {
      apikey: OLD_KEY,
      Authorization: `Bearer ${OLD_KEY}`,
    },
  });
  if (!res.ok) throw new Error(`Failed to fetch OpenAPI spec: HTTP ${res.status}`);
  return res.json();
}

// ─── Generate CREATE TABLE SQL ────────────────────────────────────────────────

function generateCreateTable(tableName: string, definition: any): string {
  const properties: Record<string, any> = definition.properties || {};
  const required: string[] = definition.required || [];

  const columns: string[] = [];

  for (const [colName, colDef] of Object.entries(properties)) {
    const pgType = toPostgresType(colDef as any);
    const notNull = required.includes(colName) ? " NOT NULL" : "";

    // Auto-detect primary key by convention (id column)
    const isPK = colName === "id";
    if (isPK && (pgType === "bigint" || pgType === "integer")) {
      columns.push(`  "${colName}" ${pgType} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`);
    } else if (isPK && pgType === "uuid") {
      columns.push(`  "${colName}" uuid DEFAULT gen_random_uuid() PRIMARY KEY`);
    } else {
      columns.push(`  "${colName}" ${pgType}${notNull}`);
    }
  }

  if (columns.length === 0) {
    return `-- Skipped '${tableName}': no column definitions found\n`;
  }

  return [
    `CREATE TABLE IF NOT EXISTS public."${tableName}" (`,
    columns.join(",\n"),
    `);`,
    `ALTER TABLE public."${tableName}" ENABLE ROW LEVEL SECURITY;`,
  ].join("\n");
}

// ─── Run SQL on the new project via Management API ───────────────────────────

async function runSQLOnNewProject(sql: string, label: string): Promise<boolean> {
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${newProjectRef}/database/query`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${PAT}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: sql }),
    }
  );

  if (!res.ok) {
    const err = await res.text();
    console.error(`  ❌ Failed to create '${label}': ${err}`);
    return false;
  }

  return true;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function run() {
  console.log("🚀 Starting schema seed...");
  console.log(`   Source:      ${OLD_URL}`);
  console.log(`   Destination: ${NEW_URL} (ref: ${newProjectRef})\n`);

  // 1. Fetch schema from old project
  console.log("📡 Fetching OpenAPI spec from old project...");
  const spec = await fetchOpenAPISpec();
  const definitions: Record<string, any> = spec.definitions || {};
  const tableNames = Object.keys(definitions).filter(
    (k) => !k.startsWith("rpc/") && definitions[k].type === "object"
  );

  console.log(`   Found ${tableNames.length} tables to create.\n`);

  let created = 0;
  let failed = 0;

  // 2. Create each table in the new project
  for (const tableName of tableNames) {
    process.stdout.write(`  🔨 Creating '${tableName}'...`);
    const sql = generateCreateTable(tableName, definitions[tableName]);
    const ok = await runSQLOnNewProject(sql, tableName);
    if (ok) {
      console.log(" ✅");
      created++;
    } else {
      failed++;
    }
  }

  console.log(`\n✅ Schema seed complete!`);
  console.log(`   Created: ${created} tables`);
  if (failed > 0) console.log(`   Failed:  ${failed} (check errors above)`);
  console.log("\n▶  Now run: npx tsx scripts/import_supabase.ts");
}

run().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
