/**
 * End-to-end J2 on Base Sepolia: the AGENT executes a policy-bound swap with
 * no owner interaction — quote → Plan → compile → preflight → session-signed
 * userOp → own relayer → journal entry read back.
 *
 * TESTNET ONLY. Agent key: EVM_AGENT_PRIVATE_KEY (generated into server/.env
 * on first run if absent — printed address only). The dev EOA plays owner,
 * relayer, and funds the account with USDC via a tiny ETH→USDC swap.
 *
 * Usage: EVM_RPC_URL=... EVM_DEPLOYER_PRIVATE_KEY=0x... [EVM_AGENT_PRIVATE_KEY=0x...] [EVM_SALT_NONCE=8]
 *        npx tsx src/scripts/evmAgentSwap.ts
 */
import { appendFileSync } from "node:fs";
import { createPublicClient, createWalletClient, encodeFunctionData, http, keccak256, parseEther, stringToHex, type Hex } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { createNonceManager, jsonRpc } from "viem/nonce";
import { baseSepolia } from "viem/chains";
import { parsePlan, parsePolicy, policyToWire } from "@corral/core";

import { swapRouter02Abi } from "../services/evm/abi/swapRouter02.js";
import { createCorralAccount } from "../services/evm/account.js";
import { uniswapV3Adapter } from "../services/evm/adapters/uniswapV3.js";
import { BASE_SEPOLIA, assertPinnedCodehashes } from "../services/evm/addresses.js";
import { preflight } from "../services/evm/execute/preflight.js";
import { localSessionSigner } from "../services/evm/execute/sessionSigner.js";
import { buildSessionUserOp, executeSessionUserOp } from "../services/evm/execute/sessionUserOp.js";
import { compilePlan } from "../services/evm/planner/compile.js";
import { composeSession } from "../services/evm/session/compose.js";
import { installSession } from "../services/evm/session/install.js";

const rpc = process.env.EVM_RPC_URL;
const ownerPk = process.env.EVM_DEPLOYER_PRIVATE_KEY as Hex | undefined;
if (!rpc || !ownerPk) throw new Error("EVM_RPC_URL and EVM_DEPLOYER_PRIVATE_KEY are required");

let agentPk = process.env.EVM_AGENT_PRIVATE_KEY as Hex | undefined;
if (!agentPk) {
  agentPk = generatePrivateKey();
  appendFileSync(".env", `\n# TESTNET agent session signer (generated by evmAgentSwap.ts)\nEVM_AGENT_PRIVATE_KEY=${agentPk}\n`);
  console.log(`generated agent key → server/.env (address ${privateKeyToAccount(agentPk).address})`);
}

const USDC = "0x036cbd53842c5426634e7929541ec2318f3dcf7e" as const;
const WETH = "0x4200000000000000000000000000000000000006" as const;
const ROUTER = "0x94cc0aac535ccdb3c01d6787d6413c739ae12bc4" as const;
const QUOTER = "0xc5290058841028f1614f3a6f0f5816cad0df5e27" as const;
const APPROVE_SEL = "0x095ea7b3" as const;
const ERC20 = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
] as const;

// Load-balanced RPCs lag on pending nonces ("replacement transaction
// underpriced" seen 2026-08-23): manage the dev EOA nonce locally.
const owner = privateKeyToAccount(ownerPk, { nonceManager: createNonceManager({ source: jsonRpc() }) });
const agent = localSessionSigner(agentPk);
const client = createPublicClient({ chain: baseSepolia, transport: http(rpc) });
const relayer = createWalletClient({ account: owner, chain: baseSepolia, transport: http(rpc) });
const adapter = uniswapV3Adapter({ router: ROUTER, quoter: QUOTER, fee: 3000 });
const saltNonce = BigInt(process.env.EVM_SALT_NONCE ?? "8");
const AMOUNT_IN = 200_000n; // 0.2 USDC per execution (testnet pool is thin)
const bal = (token: `0x${string}`, who: `0x${string}`) => client.readContract({ address: token, abi: ERC20, functionName: "balanceOf", args: [who] });

console.log("[1/8] pinned codehashes…");
await assertPinnedCodehashes(client, BASE_SEPOLIA);

// ── Owner side: account + session (J1) ───────────────────────────────────
const account = await createCorralAccount({ client, owner, saltNonce });
const now = Math.floor(Date.now() / 1000);
const targets = adapter.requiredTargets({ tokenIn: USDC, tokenOut: WETH, maxPerExecution: AMOUNT_IN, minAmountOutFloor: 1n });
const policy = parsePolicy({
  version: 1, chain_id: 84532,
  asset_scope: [{ symbol: "USDC", address: USDC }],
  budgets: [{ asset: { symbol: "USDC", address: USDC }, max_total: (AMOUNT_IN * 4n).toString() }],
  max_native_value: "0",
  target_scope: targets.map((t) => ({ ...t, param_rules: t.param_rules.map((r) => (r.rule === "LTE" ? { ...r, max: r.max.toString() } : r.rule === "GTE" ? { ...r, min: r.min.toString() } : r)) })),
  action_scope: ["APPROVE", "SWAP"],
  valid_after: now - 60, valid_until: now + 30 * 24 * 3600,
  max_executions: 4, max_executions_per_24h: 2, min_output_bps: 9500,
});
const compat = adapter.isCompatible(policy, { tokenIn: USDC, tokenOut: WETH });
if (!compat.ok) throw new Error(`adapter/policy mismatch at creation (FR-5.3): ${compat.reason}`);
const composed = composeSession({ policy, account: account.address, agentSigner: agent.address, addresses: BASE_SEPOLIA, salt: keccak256(stringToHex(`corral.agent.session.${saltNonce}`)) });
console.log(`[2/8] account ${account.address} (salt ${saltNonce}), agent ${agent.address}, permissionId ${composed.permissionId}`);

if ((await client.getBalance({ address: account.address })) < parseEther("0.003")) {
  const h = await relayer.sendTransaction({ to: account.address, value: parseEther("0.005") });
  await client.waitForTransactionReceipt({ hash: h });
}
if (!(await account.isDeployed())) {
  const r = await installSession({ client, account, composed, addresses: BASE_SEPOLIA, relayer });
  console.log(`[3/8] owner-signed install → ${r.status}${r.error ? ` (${r.error.slice(0, 200)})` : ""}`);
  if (r.status !== "ACTIVE") process.exit(1);
} else {
  console.log("[3/8] account already deployed (session assumed installed by a previous run)");
}

// ── Fund the account with USDC: dev EOA swaps a little ETH → USDC, transfers ──
if ((await bal(USDC, account.address)) < AMOUNT_IN) {
  const h1 = await relayer.writeContract({
    address: ROUTER, abi: swapRouter02Abi, functionName: "exactInputSingle",
    args: [{ tokenIn: WETH, tokenOut: USDC, fee: 3000, recipient: owner.address, amountIn: parseEther("0.003"), amountOutMinimum: 0n, sqrtPriceLimitX96: 0n }],
    value: parseEther("0.003"),
  });
  await client.waitForTransactionReceipt({ hash: h1 });
  const got = await bal(USDC, owner.address);
  const h2 = await relayer.writeContract({ address: USDC, abi: ERC20, functionName: "transfer", args: [account.address, got] });
  await client.waitForTransactionReceipt({ hash: h2 });
  console.log(`[4/8] funded account with ${got} USDC base units (dev EOA swap + transfer)`);
} else {
  console.log(`[4/8] account already holds ${await bal(USDC, account.address)} USDC base units`);
}

// ── Agent side (J2): quote → plan → compile → preflight → sign → relay ──────
const req = { account: account.address, assetIn: { symbol: "USDC", address: USDC }, assetOut: { symbol: "WETH", address: WETH }, amountIn: AMOUNT_IN, minOutputBps: policy.min_output_bps } as const;
const quote = await adapter.quote(client, req);
const actions = adapter.buildActions(req, quote);
const plan = parsePlan({
  chain_id: 84532, session_id: composed.permissionId, strategy_id: null, seq: 1,
  actions: actions.map((a) => (a.action === "APPROVE" ? { ...a, amount: a.amount.toString() } : a.action === "SWAP" ? { ...a, amount_in: a.amount_in.toString(), min_amount_out: a.min_amount_out.toString() } : a)),
});
const intentHash = keccak256(stringToHex(JSON.stringify({ policy: policyToWire(policy), intent: "DCA 1 USDC → WETH", seq: 1 })));
const compiled = compilePlan({ plan, account: account.address, adapter, addresses: BASE_SEPOLIA, intentHash });
console.log(`[5/8] quote ${quote.amountOut} wei WETH (min ${quote.minAmountOut}); plan compiled: ${compiled.executions.length} executions incl. journal`);

const pf = await preflight({ client, addresses: BASE_SEPOLIA, account: account.address, permissionId: composed.permissionId, spend: { token: USDC, approveSelector: APPROVE_SEL, amount: AMOUNT_IN }, callData: compiled.callData });
console.log(`[6/8] preflight → ${pf.ok ? "OK" : `${pf.code}: ${pf.detail}`}`, pf.snapshot ? JSON.stringify(pf.snapshot, (_, v) => (typeof v === "bigint" ? v.toString() : v)) : "");
if (!pf.ok) process.exit(1);

const usdcBefore = await bal(USDC, account.address);
const wethBefore = await bal(WETH, account.address);
const userOp = await buildSessionUserOp({ client, addresses: BASE_SEPOLIA, account: account.address, permissionId: composed.permissionId, signer: agent, callData: compiled.callData });
console.log("[7/8] agent-signed userOp → own relayer…");
const out = await executeSessionUserOp({ client, relayer, addresses: BASE_SEPOLIA }, userOp);
console.log(`      tx ${out.submission.txHash} block ${out.submission.blockNumber} op=${out.submission.opSuccess} revert=${out.submission.opRevertReason ?? "-"} gas ${out.submission.gasUsed}`);

const usdcAfter = await bal(USDC, account.address);
const wethAfter = await bal(WETH, account.address);
console.log(`[8/8] USDC ${usdcBefore} → ${usdcAfter}, WETH ${wethBefore} → ${wethAfter}; journal: ${out.journal ? `seq ${out.journal.seq} intent ${out.journal.intentHash.slice(0, 10)}… session ${out.journal.sessionId.slice(0, 10)}…` : "NONE"}`);
const ok = out.submission.opSuccess && usdcAfter === usdcBefore - AMOUNT_IN && wethAfter > wethBefore && out.journal?.intentHash === intentHash;
console.log(ok ? "J2 PROVEN: the agent executed within policy, output to the account, journaled." : "J2 FAILED");
if (!ok) process.exit(1);
